### ISSUE TITLE
Viewing the broadcast

### ISSUE THREAD

**Issue by franchesko1437** [knvk/go-vkplaybot#1]
Hello, such a question, there is a broadcast of the game, where you need to log in to your my.games account, and accordingly, when viewing from your account, they give a reward. Is there an option to attach an account login to your script?

**Comment by knvk** [comment]
Hi, 

this project focusing on chat interactions, such as moderation, ads, word games and so on. The features you are asking for are something different, and should be implemented directly in browser in my opinion. 

It's should be some kind of Better Twitch TV chrome extension, which works directly with service's web page, but for vkplay.

If we are talking about the implementation itself, then it is not difficult. Just start the listener and wait for the reward event.

**Comment by franchesko1437** [comment]
> Hi,
> 
> this project focusing on chat interactions, such as moderation, ads, word games and so on. The features you are asking for are something different, and should be implemented directly in browser in my opinion.
> 
> It's should be some kind of Better Twitch TV chrome extension, which works directly with service's web page, but for vkplay.
> 
> If we are talking about the implementation itself, then it is not difficult. Just start the listener and wait for the reward event.

The browser puts a load on the computer, so I would like to learn more about the implementation of multi-user browsing. Tell me, what is the listener mode?

**Comment by knvk** [comment]
> > Hi,
> > this project focusing on chat interactions, such as moderation, ads, word games and so on. The features you are asking for are something different, and should be implemented directly in browser in my opinion.
> > It's should be some kind of Better Twitch TV chrome extension, which works directly with service's web page, but for vkplay.
> > If we are talking about the implementation itself, then it is not difficult. Just start the listener and wait for the reward event.
> 
> The browser puts a load on the computer, so I would like to learn more about the implementation of multi-user browsing. Tell me, what is the listener mode?

Here's example for twitch:
https://github.com/night/betterttv/blob/master/src/modules/auto_claim/index.js

I guess vkplay works the same way, and you can just copy-paste the solustion, changing the neccesary css-classes.
